import Link from "next/link";
import Image from "next/image";
import { ArrowRight, Award, CheckCircle2 } from "lucide-react";
import { ServiceGrid } from "./components/service-grid";
import { SiteHeader } from "./components/site-header";
import { SiteFooter } from "./components/site-footer";
import { SeeIdleShowcase } from "./components/seeidle-showcase";
import { approvedClients } from "./data/case-studies";
import { projects } from "./data/projects";

export default function Home(){
 const featured=projects.filter(p=>p.featured).slice(0,4);
 const org={"@context":"https://schema.org","@type":"Organization",name:"Ogoldy",url:"https://www.ogoldy.com",logo:"https://www.ogoldy.com/ogoldy-wordmark.png",email:"growth@ogoldy.com",telephone:"+91 8826207270",areaServed:{"@type":"Country",name:"India"},sameAs:["http://facebook.com/OgoldyIn","https://www.linkedin.com/company/ogoldy"],award:"BW Businessworld Facility Management Excellence Awards 2026 — Emerging FM Agency of the Year"};
 return <><SiteHeader/><main><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(org)}}/>
  <section className="v9-hero"><div className="section-shell"><span className="eyebrow light">Enterprise asset transition · Pan-India</span><h1>From site requirement<br/>to <span>recovered value.</span></h1><p>Survey, decide, dismantle, move, hold, redeploy, liquidate and document—with one accountable operating partner.</p><div className="button-row"><Link className="button button-primary" href="/contact">Discuss a requirement <ArrowRight size={18}/></Link><Link className="button button-dark" href="/projects">See verified projects</Link></div><div className="hero-chain"><span>Assess</span><i>→</i><span>Decide</span><i>→</i><span>Dismantle</span><i>→</i><span>Move / hold</span><i>→</i><span>Redeploy / liquidate</span><i>→</i><span>Reinstate</span></div></div></section>
  <section className="section-shell why-ogoldy"><div><span className="eyebrow">Why Ogoldy</span><h2>One partner across the awkward handoffs.</h2><p>Enterprise exits and asset movements fail when every stage has a different owner. Ogoldy keeps the site scope and the asset decision connected.</p></div><div className="why-list">{["One survey and accountable execution plan","Every asset routed by next best use","Movement, custody and close-out remain traceable"].map(x=><div key={x}><CheckCircle2/><strong>{x}</strong></div>)}</div></section>
  <section className="section-shell v6-services"><div className="section-heading"><div><span className="eyebrow">Services</span><h2>Use one scope—or connect the full chain.</h2></div><p>From office de-fitment and industrial relocation to custody, liquidation and reinstatement.</p></div><ServiceGrid limit={6}/><div className="center-link"><Link href="/services">Explore all services <ArrowRight size={17}/></Link></div></section>
  <SeeIdleShowcase/>
  <section className="section-shell featured-projects"><div className="section-heading"><div><span className="eyebrow">Flagship projects</span><h2>Proof at enterprise scale.</h2></div><Link href="/projects">View all projects <ArrowRight size={17}/></Link></div><div className="featured-project-grid">{featured.map(p=><Link href={`/projects/${p.slug}`} key={p.slug}><Image src={p.image} alt={p.imageAlt} width={800} height={600}/><span>{p.sector} · {p.location}</span><h3>{p.client}</h3><p>{p.title}</p><div className="fact-row">{p.facts.slice(0,2).map(f=><b key={f}>{f}</b>)}</div></Link>)}</div></section>
  <section className="scale-counter" aria-label="Selected executed project scale"><div className="section-shell"><span>0</span><i>→</i><strong>1,138,000+</strong><p>sq ft across selected executed enterprise projects</p></div></section>
  <section className="client-proof v6-client-proof"><div className="section-shell"><span className="proof-label">Selected enterprise experience</span><div className="client-marquee" aria-label="Selected client names"><div>{[...approvedClients,...approvedClients].map((c,i)=><span key={c+i}>{c}</span>)}</div></div></div></section>
  <section className="recognition-section"><div className="section-shell recognition-grid"><div className="award-block"><Award/><span className="eyebrow light">Independent recognition</span><h2>Emerging FM Agency of the Year</h2><p>BW Businessworld Facility Management Excellence Awards 2026</p><a href="https://www.youtube.com/watch?v=emjHbWx-X3Q" target="_blank" rel="noreferrer">Watch the award video <ArrowRight size={17}/></a></div><div className="about-teaser"><div className="mini-orbit" aria-hidden="true"><span>O</span></div><span className="eyebrow">About Ogoldy</span><h2>Built from logistics, asset recovery and enterprise transition.</h2><p>Siddharth Gulati’s operating journey began with Pikkol, moved through enterprise asset recovery and liquidation work at Ferraille Global, and evolved into Ogoldy.</p><b>Pikkol → Ferraille Global → Ogoldy</b><Link href="/about">About Ogoldy <ArrowRight size={17}/></Link></div></div></section>
  <section className="section-shell final-cta"><div><span className="eyebrow">Start with what you have</span><h2>Share a BOQ, asset list, photos or simply the requirement.</h2></div><div className="button-row"><Link className="button button-primary" href="/contact">Start an enquiry <ArrowRight size={18}/></Link><Link className="button button-secondary" href="/asset-value-estimate">Get value estimate</Link></div></section>
 </main><SiteFooter/></>;
}
